controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_page2:
    path: /page2
    controller: ../src/Controller/Page2Controller::page2

pdf_generate:
    path: /generate-pdf
    controller: ../src/Controller/PDFController::genPDF
